#!/usr/bin/perl

# ------------------------------------------------------------------------------
use strict;
use warnings;
use utf8::all;
use open qw/:std :utf8/;

# ------------------------------------------------------------------------------
use Const::Fast;
use English qw/-no_match_vars/;
use File::Basename qw/dirname/;
use File::Which qw/which/;
use IPC::Run qw/run/;
use Path::Tiny;

use DDP;

# ------------------------------------------------------------------------------
const my $PERLTIDY => ( which 'perltidy' )[0];
const my $P_U_S    => dirname($PROGRAM_NAME) . '/perl-use-sort.pl';
const my $LOG      => path('/tmp/perltidy.log');

# ------------------------------------------------------------------------------
our $VERSION = 'v1.0';

# ------------------------------------------------------------------------------
$LOG->append( ( np @ARGV ) . "\n" );

my $perm = ( stat $ARGV[-1] )[2] & 07777;

my ( $stdout, $stderr );

run [ $P_U_S, $ARGV[-1] ], sub { }, \$stdout, \$stderr;
$stderr and $LOG->append("$stderr\n");

run [ $PERLTIDY, @ARGV ], sub { }, sub { }, \$stderr;
$stderr and $LOG->append("$stderr\n");

chmod $perm, $ARGV[-1];

exit 0;

# ------------------------------------------------------------------------------
__END__

=head1 DESCRIPTION
    Замена системного perltidy. Отлаживалось как внешняя утилита
    для Eclipse, в других случаях не гонялось.
    Предварительно стотирует блоки "use ..." по алфавиту.

    Использование:
        perltidy [аргументы /usr/bin/perltidy] имя_файла
=cut

# ------------------------------------------------------------------------------
